package: media_manager_plus
version: '1.0.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/media_manager_plus

page:
    title: 'translate:title'
    perm: media_manager_plus[]
    pjax: true
    icon: rex-icon rex-icon-media
    subpages:
        groups: { title: 'translate:groups', perm: media_manager_plus[groups] }